---
 - name: Install Prerequisites for Docker Ce
   package:  name={{ item }}
   with_items:
      - yum-utils 
      - device-mapper-persistent-data 
      - lvm2
      - policycoreutils-python

 - name: Download container-selinux rpm
   get_url: url=http://mirror.centos.org/centos/7/extras/x86_64/Packages/container-selinux-2.21-1.el7.noarch.rpm dest=/root

 - name: Install RPM
   shell: rpm -qi container-selinux
   register: result

 - name: Install Container rpm
   command: rpm -i /root/container-selinux-2.21-1.el7.noarch.rpm
   when: "result.stdout.find('Install Date: (not installed)') != -1" 

 - name: Disabe selinux
   selinux: state=disabled

 - name: Enable extra Repo
   command: yum-config-manager --enable centos-extras

 - name: Add docker repo
   get_url: url=https://download.docker.com/linux/centos/docker-ce.repo  dest=/etc/yum.repos.d/

 - name: Installing Docker 
   package: name=docker-ce state=present

 - name: Installing Docker Compose
   command: curl -L https://github.com/docker/compose/releases/download/1.18.0/docker-compose-Linux-x86_64  -o /usr/local/bin/docker-compose 

 - name: Give Executive permission to compose
   file: path=/usr/local/bin/docker-compose mode=775

 - name: Download Docker machine
   command: curl -L https://github.com/docker/machine/releases/download/v0.13.0/docker-machine-Linux-x86_64 -o /tmp/docker-machine

 - name: Give Executive permission to machine
   file: path=/tmp/docker-machine mode=775

 - name: Copy docker-machine file to bin dir 
   copy: src=/tmp/docker-machine dest=/usr/local/bin/ remote_src=yes


 - name: Start Docker 
   service: name=docker state=started

 - name: "get docker info"
   shell: docker info
   register: docker_info
   changed_when: False

 - name: create primary swarm manager
   shell: docker swarm init --advertise-addr {{ ansible_eth0['ipv4']['address'] }}
   when: "docker_info.stdout.find('Swarm: inactive') != -1"
 
 - name: "get docker swarm worker token"
   shell: docker swarm join-token -q worker
   register: worker_token
