---
 - name: Install Prerequisites for Docker Ce
   package:  name={{ item }}
   with_items:
      - yum-utils 
      - device-mapper-persistent-data 
      - lvm2
      - policycoreutils-python

 - name: Download container-selinux rpm
   get_url: url=http://mirror.centos.org/centos/7/extras/x86_64/Packages/container-selinux-2.21-1.el7.noarch.rpm dest=/root

 - name: Query RPM
   shell: rpm -qi container-selinux
   register: result

 - name: Install Rpm
   command: rpm -i /root/container-selinux-2.21-1.el7.noarch.rpm
   when: "result.stdout.find('Install Date: (not installed)') != -1"

 - name: Disabe selinux
   selinux: state=disabled

 - name: Enable extra Repo
   command: yum-config-manager --enable centos-extras

 - name: Add docker repo
   get_url: url=https://download.docker.com/linux/centos/docker-ce.repo  dest=/etc/yum.repos.d/

 - name: Installing Docker 
   package: name=docker-ce state=present


 - name: Start Docker 
   service: name=docker state=started

 - name: Docker info
   shell: docker info
   register: docker_node
   changed_when: False    

 - name: "join as a worker"
   shell: "docker swarm join --token {{ hostvars['manager']['worker_token']['stdout'] }} {{ hostvars['manager']['ansible_eth0']['ipv4']['address'] }}:2377"
   when: "docker_node.stdout.find('Swarm: inactive') != -1"
   retries: 3
   delay: 20
